import { describe, expect, it } from "vitest";
import {
  DEFAULT_SUMMARY_TEMPLATE,
  type SummaryFieldKey,
} from "./summaryTemplate";
import { formatFolderSummary, type FolderSummaryTask } from "./folderSummary";
import type { Folder, Task } from "./types";

const folder: Folder = {
  id: "folder-1",
  name: "Q1 roadmap",
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-15T00:00:00Z",
};

const baseTask: Task = {
  id: "task-1",
  title: "Ship the summary template",
  descriptionMarkdown: "",
  status: "active",
  nextStep: null,
  estimatedMinutes: 8 * 60,
  folderId: "folder-1",
  createdAt: "2025-01-01T09:00:00Z",
  updatedAt: "2025-01-02T12:30:00Z",
};

const FIXED_NOW = new Date("2025-01-15T14:30:00Z");

describe("formatFolderSummary", () => {
  it("renders a header, one section per task, and a footer", () => {
    const items: FolderSummaryTask[] = [
      { task: baseTask, context: { totalMinutes: 270 } },
    ];
    const out = formatFolderSummary(
      folder,
      items,
      DEFAULT_SUMMARY_TEMPLATE,
      FIXED_NOW,
    );
    expect(out).toMatch(/^# Q1 roadmap — /);
    expect(out).toContain("## Task: Ship the summary template");
    expect(out).toContain("- **Status:** Active");
    expect(out).toContain("- **Estimate:** 1d");
    expect(out).toContain("- **Logged:** 4h 30m");
    expect(out).toMatch(/\n---\nGenerated by DevThread at /);
  });

  it("separates tasks with blank lines", () => {
    const items: FolderSummaryTask[] = [
      { task: baseTask, context: { totalMinutes: 30 } },
      {
        task: { ...baseTask, id: "task-2", title: "Wire the folder menu" },
        context: { totalMinutes: 60 },
      },
    ];
    const out = formatFolderSummary(
      folder,
      items,
      DEFAULT_SUMMARY_TEMPLATE,
      FIXED_NOW,
    );
    const task1End =
      out.indexOf("## Task: Ship the summary template") +
      "## Task: Ship the summary template".length;
    const task2Start = out.indexOf("## Task: Wire the folder menu");
    expect(task1End).toBeGreaterThan(0);
    expect(task2Start).toBeGreaterThan(task1End);
    expect(out.slice(task1End, task2Start)).toMatch(/\n\n/);
  });

  it("renders a placeholder body for empty folders", () => {
    const out = formatFolderSummary(
      folder,
      [],
      DEFAULT_SUMMARY_TEMPLATE,
      FIXED_NOW,
    );
    expect(out).toContain("_No tasks in this folder._");
  });

  it("respects the template toggles inside each task section", () => {
    const items: FolderSummaryTask[] = [
      {
        task: baseTask,
        context: {
          totalMinutes: 270,
          entries: [{ contentMarkdown: "Did the thing", durationMinutes: 270 }],
        },
      },
    ];
    const lean = formatFolderSummary(
      folder,
      items,
      DEFAULT_SUMMARY_TEMPLATE,
      FIXED_NOW,
    );
    expect(lean).not.toContain("Did the thing");

    const verbose = formatFolderSummary(
      folder,
      items,
      { ...DEFAULT_SUMMARY_TEMPLATE, worklogEntries: true },
      FIXED_NOW,
    );
    expect(verbose).toContain("- 4h 30m Did the thing");
  });

  it("always shows the task title as a section header, even when Title toggle is off", () => {
    const out = formatFolderSummary(
      folder,
      [{ task: baseTask, context: {} }],
      { ...DEFAULT_SUMMARY_TEMPLATE, title: false },
      FIXED_NOW,
    );
    expect(out).toContain("## Task: Ship the summary template");
    expect(out).not.toContain("- **Title:**");
  });

  it("respects a custom field order inside each section", () => {
    const order: ReadonlyArray<SummaryFieldKey> = [
      "title",
      "estimate",
      "status",
      "worklog",
      "worklogEntries",
      "quickLinks",
      "createdDate",
      "updatedDate",
    ];
    const out = formatFolderSummary(
      folder,
      [{ task: baseTask, context: { totalMinutes: 60 } }],
      DEFAULT_SUMMARY_TEMPLATE,
      FIXED_NOW,
      order,
    );
    const section = out.split("## Task: Ship the summary template\n")[1];
    const lines = section.split("\n");
    expect(lines[1]).toBe("- **Estimate:** 1d");
    expect(lines[2]).toBe("- **Status:** Active");
    expect(lines[3]).toBe("- **Logged:** 1h");
  });
});
