import { describe, expect, it } from "vitest";
import { formatFolderSummary, type FolderSummaryTask } from "./folderSummary";
import type { Folder, Task } from "./types";

const folder: Folder = {
  id: "folder-1",
  name: "Q1 roadmap",
  releaseName: null,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-15T00:00:00Z",
};

const baseTask: Task = {
  id: "task-1",
  title: "Ship the summary template",
  descriptionMarkdown: "",
  status: "active",
  nextStep: null,
  estimatedMinutes: 8 * 60,
  folderId: "folder-1",
  releaseName: null,
  createdAt: "2025-01-01T09:00:00Z",
  updatedAt: "2025-01-02T12:30:00Z",
};

const FIXED_NOW = new Date("2025-01-15T14:30:00Z");

describe("formatFolderSummary", () => {
  it("renders a header, a task table, and a footer", () => {
    const items: FolderSummaryTask[] = [
      { task: baseTask, totalMinutes: 270 },
    ];
    const out = formatFolderSummary(folder, items, undefined, FIXED_NOW);
    expect(out).toMatch(/^# Q1 roadmap — /);
    expect(out).toContain("| Ship the summary template");
    expect(out).toContain("Active");
    expect(out).toContain("1d");
    expect(out).toContain("4h 30m");
    expect(out).toMatch(/\n---\nGenerated by DevThread at /);
  });

  it("includes Folder column only when tasks have a folderId", () => {
    const items: FolderSummaryTask[] = [
      { task: baseTask, totalMinutes: 30 },
    ];
    const out = formatFolderSummary(folder, items, undefined, FIXED_NOW);
    expect(out).toContain("| Folder |");
  });

  it("omits Folder column when no task has a folderId", () => {
    const items: FolderSummaryTask[] = [
      { task: { ...baseTask, folderId: null }, totalMinutes: 30 },
    ];
    const out = formatFolderSummary(folder, items, undefined, FIXED_NOW);
    expect(out).not.toContain("| Folder |");
  });

  it("omits Estimate column when no task has estimate", () => {
    const items: FolderSummaryTask[] = [
      { task: { ...baseTask, estimatedMinutes: null, folderId: null }, totalMinutes: 30 },
    ];
    const out = formatFolderSummary(folder, items, undefined, FIXED_NOW);
    expect(out).not.toContain("| Est. |");
  });

  it("omits Logged column when nothing is logged", () => {
    const items: FolderSummaryTask[] = [
      { task: { ...baseTask, folderId: null }, totalMinutes: 0 },
    ];
    const out = formatFolderSummary(folder, items, undefined, FIXED_NOW);
    expect(out).not.toContain("| Logged |");
  });

  it("crops long titles to 60 characters", () => {
    const items: FolderSummaryTask[] = [
      {
        task: {
          ...baseTask,
          folderId: null,
          title: "A really really really really really long task title that exceeds the maximum allowed length for display",
        },
      },
    ];
    const out = formatFolderSummary(folder, items, undefined, FIXED_NOW);
    const cropped = out.match(/\| (.{59})… \|/)?.[1];
    expect(cropped).toBeTruthy();
    expect(cropped!.length).toBe(59);
  });

  it("renders a placeholder body for empty folders", () => {
    const out = formatFolderSummary(folder, [], undefined, FIXED_NOW);
    expect(out).toContain("_No tasks in this folder._");
  });
});
