import { formatTaskTable, type TaskTableRow } from "./taskTable";
import type { Folder } from "./types";

export interface FolderSummaryTask extends TaskTableRow {
  task: import("./types").Task;
  context?: { totalMinutes?: number };
}

export function formatFolderSummary(
  folder: Folder,
  tasks: FolderSummaryTask[],
  _template?: unknown,
  now: Date = new Date(),
  _order?: unknown,
) {
  const header = `# ${folder.name} — ${formatLongDate(now)}`;
  const body = tasks.length
    ? formatTaskTable(
        tasks.map((t) => ({
          task: t.task,
          totalMinutes: t.context?.totalMinutes ?? t.totalMinutes,
        })),
      )
    : "_No tasks in this folder._";
  const footer = `Generated by DevThread at ${formatTime(now)}`;
  return [header, body].join("\n\n") + "\n\n---\n" + footer;
}

export async function copyFolderSummary(
  folder: Folder,
  tasks: FolderSummaryTask[],
  _template?: unknown,
  _order?: unknown,
) {
  await writeClipboard(
    formatFolderSummary(folder, tasks, undefined, new Date()),
  );
}

function formatLongDate(date: Date) {
  return date.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatTime(date: Date) {
  return date.toLocaleTimeString(undefined, {
    hour: "numeric",
    minute: "2-digit",
  });
}

async function writeClipboard(value: string) {
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(value);
    return;
  }
  if (typeof document === "undefined") return;
  const textarea = document.createElement("textarea");
  textarea.value = value;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}
