import {
  DEFAULT_SUMMARY_TEMPLATE,
  type SummaryTemplate,
} from "./summaryTemplate";
import { formatTaskSection, type TaskSummaryContext } from "./taskSummary";
import type { Folder } from "./types";

export interface FolderSummaryTask {
  task: import("./types").Task;
  context: TaskSummaryContext;
}

export function formatFolderSummary(
  folder: Folder,
  tasks: FolderSummaryTask[],
  template: SummaryTemplate = DEFAULT_SUMMARY_TEMPLATE,
  now: Date = new Date(),
) {
  const header = formatFolderHeader(folder, now);
  const body = tasks.length
    ? tasks
        .map((item) => formatTaskSection(item.task, item.context, template))
        .join("\n\n")
    : "_No tasks in this folder._";
  const footer = `Generated by DevThread at ${formatTime(now)}`;
  return [header, body].join("\n\n") + "\n\n---\n" + footer;
}

export async function copyFolderSummary(
  folder: Folder,
  tasks: FolderSummaryTask[],
  template?: SummaryTemplate,
) {
  const { loadSummaryTemplate } = await import("./summaryTemplate");
  const effectiveTemplate = template ?? loadSummaryTemplate();
  await writeClipboard(formatFolderSummary(folder, tasks, effectiveTemplate));
}

function formatFolderHeader(folder: Folder, now: Date) {
  return `# ${folder.name} — ${formatLongDate(now)}`;
}

function formatLongDate(date: Date) {
  return date.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatTime(date: Date) {
  return date.toLocaleTimeString(undefined, {
    hour: "numeric",
    minute: "2-digit",
  });
}

async function writeClipboard(value: string) {
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(value);
    return;
  }
  if (typeof document === "undefined") return;
  const textarea = document.createElement("textarea");
  textarea.value = value;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}
